### ISSUE TITLE
AGP 8.x support

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/slack-gradle-plugin#184]

**Comment by ZacSweers** [comment]
```
java.lang.NoSuchMethodError: 'com.android.build.api.dsl.JniLibsPackagingOptions com.android.build.api.dsl.PackagingOptions.getJniLibs()'
        at slack.gradle.StandardProjectConfigurations$configureAndroidProjects$2$3$3.invoke(StandardProjectConfigurations.kt:574)
        at slack.gradle.StandardProjectConfigurations$configureAndroidProjects$2$3$3.invoke(StandardProjectConfigurations.kt:105)
        at com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated.packagingOptions(Unknown Source)
        at com.android.build.gradle.internal.dsl.BaseAppModuleExtension.packagingOptions(BaseAppModuleExtension.kt)
        at slack.gradle.StandardProjectConfigurations$configureAndroidProjects$2$3.invoke(StandardProjectConfigurations.kt:553)
        at slack.gradle.StandardProjectConfigurations$configureAndroidProjects$2$3.invoke(StandardProjectConfigurations.kt:105)
        at slack.gradle.StandardProjectConfigurations$configureAndroidProjects$2.execute(StandardProjectConfigurations.kt:1257)

```

**Comment by ZacSweers** [comment]
I believe this is fixed on main now
