### ISSUE TITLE
Apple Silicon thermal throttling doesn't work in Gradle 8.0-rc-2+

### ISSUE THREAD

**Issue by ZacSweers** [slackhq/slack-gradle-plugin#239]
```
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsatisfiedLinkError: Unable to load library 'thermal_state':
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/System/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'thermal_state':
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/System/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.Native.load(Native.java:596)
	at slack.gradle.util.JnaThermalState$Companion.<clinit>(ThermalsWatcher.kt:382)
	at slack.gradle.util.JnaThermalState.<clinit>(ThermalsWatcher.kt)
	at slack.gradle.util.AppleSiliconThermals.getThermalState(ThermalsWatcher.kt:338)
	at slack.gradle.util.AppleSiliconThermals.access$getThermalState(ThermalsWatcher.kt:267)
	at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:288)
	at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:267)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:35)
	... 6 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 19 more
Exception in thread "RxComputationThreadPool-1" io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.UnsatisfiedLinkError: Unable to load library 'thermal_state':
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/System/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'thermal_state':
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/System/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
	at com.sun.jna.Library$Handler.<init>(Library.java:197)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.Native.load(Native.java:596)
	at slack.gradle.util.JnaThermalState$Companion.<clinit>(ThermalsWatcher.kt:382)
	at slack.gradle.util.JnaThermalState.<clinit>(ThermalsWatcher.kt)
	at slack.gradle.util.AppleSiliconThermals.getThermalState(ThermalsWatcher.kt:338)
	at slack.gradle.util.AppleSiliconThermals.access$getThermalState(ThermalsWatcher.kt:267)
	at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:288)
	at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:267)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:35)
	... 6 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 19 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:268)
		... 19 more
```

**Comment by ZacSweers** [comment]
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class slack.gradle.util.JnaThermalState
        at slack.gradle.util.AppleSiliconThermals.getThermalState(ThermalsWatcher.kt:338)
        at slack.gradle.util.AppleSiliconThermals.access$getThermalState(ThermalsWatcher.kt:267)
        at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:288)
        at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:267)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:35)
        ... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'thermal_state':
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache)
dlopen(/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Users/zacsweers/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Library/Frameworks/thermal_state.framework/thermal_state' (no such file, not in dyld cache)
dlopen(/Library/Frameworks/thermal_state.framework/thermal_state, 0x0009): tried: '/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/thermal_state.framework/thermal_state' (no such file), '/Library/Frameworks/thermal_state.framework/thermal_s
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483)
        at com.sun.jna.Library$Handler.<init>(Library.java:197)
        at com.sun.jna.Native.load(Native.java:622)
        at com.sun.jna.Native.load(Native.java:596)
        at slack.gradle.util.JnaThermalState$Companion.<clinit>(ThermalsWatcher.kt:382)
        at slack.gradle.util.JnaThermalState.<clinit>(ThermalsWatcher.kt)
        ... 13 more
Exception in thread "RxComputationThreadPool-8" io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoClassDefFoundError: Could not initialize class slack.gradle.util.JnaThermalState
        at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:41)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class slack.gradle.util.JnaThermalState
        at slack.gradle.util.AppleSiliconThermals.getThermalState(ThermalsWatcher.kt:338)
        at slack.gradle.util.AppleSiliconThermals.access$getThermalState(ThermalsWatcher.kt:267)
        at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:288)
        at slack.gradle.util.AppleSiliconThermals$start$2.apply(ThermalsWatcher.kt:267)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:35)
        ... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'thermal_state':
dlopen(libthermal_state.dylib, 0x0009): tried: 'libthermal_state.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/./libthermal_state.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu-19.jdk/Contents/Home/bin/../lib/libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache), 'libthermal_state.dylib' (no such file), '/usr/lib/libthermal_state.dylib' (no such file, not in dyld cache
```

**Comment by ZacSweers** [comment]
Seems like it was just a ghost in the machine, can't reproduce it now

**Comment by bilgehankalkan** [comment]
This happened to me when I didn't run `regenerate_thermals_lib.sh` or created `libthermal_state.dylib` without script.
